'use client'

import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'
import { DynamicIcon, type IconName } from 'lucide-react/dynamic'
import Link from 'next/link'

type FAQItem = {
    id: string
    icon: IconName
    question: string
    answer: string
}

export default function FAQsThree() {
    const faqItems: FAQItem[] = [
        {
            id: 'item-1',
            icon: 'graduation-cap',
            question: 'How does Luna help with my assignments?',
            answer: 'Luna uses advanced AI to help you create well-structured, properly formatted academic assignments. Simply provide your topic, requirements, and academic level, and Luna will generate high-quality content with proper citations and formatting.',
        },
        {
            id: 'item-2',
            icon: 'credit-card',
            question: 'How does Luna pricing work?',
            answer: 'Luna offers a free Student plan with 1 assignment as a trial, and most importantly assignment credits that allow students to be done with their assignments very quick.',
        },
        {
            id: 'item-3',
            icon: 'clock',
            question: 'How quickly can Luna generate my assignment?',
            answer: 'Most assignments are generated within 1-5 minutes, depending on length and complexity. It all depends on the type of assignment credits - quick ones go first then regural ones. You\'ll receive updates on the progress.',
        },
        {
            id: 'item-4',
            icon: 'shield-check',
            question: 'Is Luna content original and plagiarism-free?',
            answer: 'Yes, all content generated by Luna is original and created specifically for your assignment. It also humanizes the content it generates so then it is almost indistinguishable from human writings.',
        },
        {
            id: 'item-5',
            icon: 'book-open',
            question: 'What types of assignments can Luna help with?',
            answer: 'Almost all types - most university and college assignments.',
        },
    ]

    return (
        <section className="bg-muted dark:bg-background py-20">
            <div className="mx-auto max-w-5xl px-4 md:px-6">
                <div className="flex flex-col gap-10 md:flex-row md:gap-16">
                    <div className="md:w-1/3">
                        <div className="sticky top-20">
                            <h2 className="mt-4 text-3xl font-bold">Frequently Asked Questions</h2>
                            <p className="text-muted-foreground mt-4">
                                Can't find what you're looking for? Contact our{' '}
                                <Link
                                    href="#"
                                    className="text-primary font-medium hover:underline">
                                    customer support team
                                </Link>
                            </p>
                        </div>
                    </div>
                    <div className="md:w-2/3">
                        <Accordion
                            type="single"
                            collapsible
                            className="w-full space-y-2">
                            {faqItems.map((item) => (
                                <AccordionItem
                                    key={item.id}
                                    value={item.id}
                                    className="bg-background shadow-xs rounded-lg border px-4 last:border-b">
                                    <AccordionTrigger className="cursor-pointer items-center py-5 hover:no-underline">
                                        <div className="flex items-center gap-3">
                                            <div className="flex size-6">
                                                <DynamicIcon
                                                    name={item.icon}
                                                    className="m-auto size-4"
                                                />
                                            </div>
                                            <span className="text-base font-bold">{item.question}</span>
                                        </div>
                                    </AccordionTrigger>
                                    <AccordionContent className="pb-5">
                                        <div className="px-9">
                                            <p className="text-base">{item.answer}</p>
                                        </div>
                                    </AccordionContent>
                                </AccordionItem>
                            ))}
                        </Accordion>
                    </div>
                </div>
            </div>
        </section>
    )
}
